#!/bin/bash
# fix_permisos.sh — ROBOTSchool Academy Learning
# Ejecutar desde la carpeta del proyecto:
# sudo bash fix_permisos.sh

PROYECTO="$(cd "$(dirname "$0")" && pwd)"
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║   ROBOTSchool Academy — Fix Permisos         ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "Proyecto detectado en: $PROYECTO"
echo ""

# ── CREAR CARPETAS ───────────────────────────────────────
echo "▶ Creando carpetas..."
mkdir -p "$PROYECTO/assets/img"
mkdir -p "$PROYECTO/assets/css"
mkdir -p "$PROYECTO/assets/js"
mkdir -p "$PROYECTO/uploads/cursos"
mkdir -p "$PROYECTO/uploads/cursos/galeria"
mkdir -p "$PROYECTO/uploads/estudiantes"
mkdir -p "$PROYECTO/uploads/comprobantes"
mkdir -p "$PROYECTO/config"
mkdir -p "$PROYECTO/includes"
mkdir -p "$PROYECTO/public"
mkdir -p "$PROYECTO/portal"
mkdir -p "$PROYECTO/modulos/cursos"
mkdir -p "$PROYECTO/modulos/grupos"
mkdir -p "$PROYECTO/modulos/equipos"
mkdir -p "$PROYECTO/modulos/estudiantes"
mkdir -p "$PROYECTO/modulos/padres"
mkdir -p "$PROYECTO/modulos/matriculas"
mkdir -p "$PROYECTO/modulos/pagos"
mkdir -p "$PROYECTO/modulos/evaluaciones"
mkdir -p "$PROYECTO/modulos/rubricas"
mkdir -p "$PROYECTO/modulos/sedes"
mkdir -p "$PROYECTO/modulos/usuarios"
mkdir -p "$PROYECTO/modulos/reportes"
echo "   ✅ Carpetas listas"

# ── PERMISOS ────────────────────────────────────────────
echo ""
echo "▶ Aplicando permisos..."
chmod 777 "$PROYECTO/assets/img"
chmod 755 "$PROYECTO/assets/css"
chmod 755 "$PROYECTO/assets/js"
chmod -R 777 "$PROYECTO/uploads"
chmod -R 755 "$PROYECTO/config"
chmod -R 755 "$PROYECTO/includes"
chmod -R 755 "$PROYECTO/modulos"
chmod -R 755 "$PROYECTO/public"
chmod 644 "$PROYECTO"/*.php 2>/dev/null || true
chmod 644 "$PROYECTO"/*.sql 2>/dev/null || true
echo "   ✅ Permisos aplicados"

echo ""
echo "════════════════════════════════════════════════"
echo "✅  Todo listo."
echo ""
echo "  uploads/cursos/galeria/ → 777 ✓"
echo "  uploads/estudiantes/    → 777 ✓"
echo "  uploads/comprobantes/   → 777 ✓"
echo "  assets/img/             → 777 ✓"
echo ""
echo "  Logo aqui:"
echo "  $PROYECTO/assets/img/logo_oficial.png"
echo ""
echo "  URL:"
echo "  http://localhost/$(basename $PROYECTO)/"
echo "════════════════════════════════════════════════"
